import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Auction House",
  description: "Generated by create next app",
  icons:{
    icon: "/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" type="image/png" href="/favicon.ico" />
    </head>
    <body>
      {children}
    </body>
  </html>
  
  );
}
